#!/usr/bin/env python3
"""
GPUOpt CSV Parser

Parses CSV output generated by NVIDIA Nsight Compute CLI (ncu).
"""

import csv
import os
from io import StringIO
from typing import List, Dict, Any


class CSVParser:
    """Parses Nsight Compute CSV export files."""
    
    def parse(self, filepath_or_content: str) -> List[Dict[str, Any]]:
        """
        Parse CSV file or string content into raw kernel profile dictionary records.
        """
        if os.path.exists(filepath_or_content):
            with open(filepath_or_content, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
        else:
            content = filepath_or_content
            
        # Clean up non-CSV preamble lines
        lines = content.splitlines()
        csv_lines = [line for line in lines if line.startswith('"') or ',' in line]
        clean_content = '\n'.join(csv_lines)
        
        reader = csv.DictReader(StringIO(clean_content))
        
        kernels_data: Dict[str, Dict[str, Any]] = {}
        
        for row in reader:
            if not row or 'Kernel Name' not in row or not row.get('Kernel Name'):
                continue
                
            raw_kname = row.get('Kernel Name', 'UnknownKernel')
            kernel_id = row.get('ID', '0')
            key = f"{kernel_id}_{raw_kname}"
            
            if key not in kernels_data:
                kernels_data[key] = {
                    'id': kernel_id,
                    'kernel_name': raw_kname,
                    'device': row.get('Device', '0'),
                    'cc': row.get('CC', '0.0'),
                    'block_size': row.get('Block Size', ''),
                    'grid_size': row.get('Grid Size', ''),
                    'metrics': {},
                    'rules': []
                }
                
            metric_name = (row.get('Metric Name') or '').strip()
            metric_val = (row.get('Metric Value') or '').strip()
            metric_unit = (row.get('Metric Unit') or '').strip()
            
            if metric_name and metric_val != '':
                parsed_val = self._parse_number(metric_val)
                kernels_data[key]['metrics'][metric_name] = {
                    'val': parsed_val,
                    'raw': metric_val,
                    'unit': metric_unit,
                    'section': row.get('Section Name', '')
                }
                
            rule_name = (row.get('Rule Name') or '').strip()
            rule_desc = (row.get('Rule Description') or '').strip()
            if rule_name and rule_desc:
                kernels_data[key]['rules'].append({
                    'rule_name': rule_name,
                    'rule_type': row.get('Rule Type', ''),
                    'description': rule_desc,
                    'speedup_type': row.get('Estimated Speedup Type', ''),
                    'estimated_speedup': row.get('Estimated Speedup', '')
                })
                
        return list(kernels_data.values())

    def get_kernels(self, parsed_data: List[Dict[str, Any]]) -> List[str]:
        """Extract unique list of kernel names from parsed data."""
        return [k['kernel_name'] for k in parsed_data]

    @staticmethod
    def _parse_number(val_str: str) -> Any:
        """Parse string containing formatted numbers into float or int."""
        cleaned = val_str.replace(',', '').strip()
        try:
            if '.' in cleaned:
                return float(cleaned)
            return int(cleaned)
        except ValueError:
            return val_str
