#!/usr/bin/env python3
"""
GPUOpt Parser Data Models

Defines data structures representing raw profiler output, normalized kernel metrics,
and analysis diagnostics.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional


@dataclass
class DeviceInfo:
    """Information about target GPU device."""
    name: str = "Unknown GPU"
    compute_capability: str = "0.0"
    device_id: int = 0


@dataclass
class NsightRuleAdvisory:
    """Built-in rule alert generated by Nsight Compute."""
    rule_name: str
    rule_type: str
    description: str
    speedup_type: Optional[str] = None
    estimated_speedup: Optional[str] = None


@dataclass
class KernelProfileData:
    """Normalized profiling data for a single CUDA kernel launch."""
    name: str
    demangled_name: str
    device_info: DeviceInfo
    block_size: str = ""
    grid_size: str = ""
    
    # Normalized metric categories
    execution_metrics: Dict[str, Any] = field(default_factory=dict)
    memory_metrics: Dict[str, Any] = field(default_factory=dict)
    compute_metrics: Dict[str, Any] = field(default_factory=dict)
    occupancy_metrics: Dict[str, Any] = field(default_factory=dict)
    
    # Raw key-value metrics
    raw_metrics: Dict[str, Any] = field(default_factory=dict)
    
    # Built-in Nsight rule alerts
    nsight_rules: List[NsightRuleAdvisory] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert kernel profile data to dictionary."""
        return {
            "name": self.name,
            "demangled_name": self.demangled_name,
            "device": {
                "name": self.device_info.name,
                "compute_capability": self.device_info.compute_capability,
                "device_id": self.device_info.device_id,
            },
            "block_size": self.block_size,
            "grid_size": self.grid_size,
            "execution": self.execution_metrics,
            "memory": self.memory_metrics,
            "compute": self.compute_metrics,
            "occupancy": self.occupancy_metrics,
            "raw_metrics": self.raw_metrics,
            "nsight_rules": [
                {
                    "rule_name": r.rule_name,
                    "rule_type": r.rule_type,
                    "description": r.description,
                    "speedup_type": r.speedup_type,
                    "estimated_speedup": r.estimated_speedup
                } for r in self.nsight_rules
            ]
        }
